"""Pack the approved after-face PNG frames generated by render-pair-hero.mjs."""
from pathlib import Path
from PIL import Image

output = Path('public/live/cards/pair')
output.mkdir(exist_ok=True)
atlas = Image.new('RGBA', (2400, 2160))
for index in range(30):
    frame = Image.open(f'outputs/pair-hero/{index}.png').convert('RGBA')
    assert frame.size == (480, 360)
    atlas.paste(frame, (index % 5 * 480, index // 5 * 360))
atlas.save(output / 'hero.webp', lossless=True, method=6)
Image.open('outputs/pair-hero/29.png').save(output / 'poster.webp', lossless=True, method=6)
